"""add role column to users

Revision ID: a31d62e3fbf1
Revises: cfb916578745
Create Date: 2026-06-11 19:20:23.021825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a31d62e3fbf1'
down_revision: Union[str, Sequence[str], None] = 'cfb916578745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column as nullable first
    op.add_column(
        "users",
        sa.Column("role", sa.String(), nullable=True)
    )

    # Populate existing rows
    op.execute(
        "UPDATE users SET role = 'guest' WHERE role IS NULL"
    )

    # Make column NOT NULL
    op.alter_column(
        "users",
        "role",
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
